// ON PLAYER KILLED ///////////////////////////////////////////////////////////////////////////////
/*
	- Executed locally when player is killed in mission.
*/
///////////////////////////////////////////////////////////////////////////////////////////////////

quotes = [
	"""All warfare is based""<br/>-Sun Tzu",
	"""Bees make honey""<br/>-DJ Smokey",
	"""Man, seventy-five meters, front!""<br/>-SSgt. Adams",
	"""I want to say 'I need to go to bed' but my mouth keeps<br/>fighting me and trying to say 'I need to kill myself'""<br/>-Remerv Keberb",
	"""The man on top bunk [in] 2019 wanked hard<br/>every night and this bed fucking SHOOK""<br/>-message sharpied on the underside of a barracks bedframe",
	"""STROHEIM! AM I SPEAKING FUCKING CHINESE!?!?""<br/>-Croguy",
	"""the diode will perform differently if<br/>the temperature of your ambien changes""<br/>-my Industrial Electronics teacher",
	"""AI is talking to me""<br/>-my Industrial Electronics teacher, unprompted",
	"""Any Groups that consist soley of combat veterans over the age of 30? I hate civilians. Also no Air Force.""<br/>-Ando",
	"""they can it a tnak cuz yuouo tank in the ntsak""<br/>-Exabit",
	"""I killed a lot of people ! I wish I could tell their wives myself !!""<br/>-Snubby",
	"""you know it<br/>fuckifgn IDIOT mods""<br/>-Pilotguy",
	"""Worse comes to worst I'm gonna turn into a catboy and purr down the LR until we all die""<br/>-Asortied",
	"""Don't dead open my ass or whatever""<br/>-Barkhan",
	"""we’re currently clean on opsec""<br/>-Pete Hegseth",
	"""Come for the vaseline, stay for how uncut it is!""<br/>-Milo Rossi",
	"""The mitochondria is the powerhouse of the cell""<br/>-A science teacher",
	"""very hot im wanking at my desk as we speak""<br/>-lelop",
	"""MRREEOW""<br/>-Valiant's cat",
	"""Can I join yet?""<br/>-Joint Op Player",
	"""Watch the backblast, you idiot""<br/>-Sun Tzu",
	"""I'm 19 years old and I've already wasted my entire life""<br/>-burguerpants",
	"""First we mine, then we craft, LETS MINECRAFT""<br/>-Jack Black",
	"""youll be fine<br/>we love ya<br/>i am in hell""<br/>-Neo",
	"""ur ur ur ur""<br/>-Freddy Fazbear",
	"""<u>Why</u> is it called nine eleven?""<br/>-Davit Foxtrot",
	"""Why do they call it oven when you of in the cold food of out hot eat the food""<br/>-Jon",
	"""in war, there are no unpissed soldiers""<br/>-Honey Butter",
	"""Who fucking keeps removing hornet pussy?""<br/>-Barkhan",
	"""PROTIP: To defeat the Cyberdemon, shoot at it until it dies""<br/>-Andrew Stine",
	"""Friendly fire isn't""<br/>-Murphy's Laws of Combat",
	"""Well, THAT just happened""<br/>-Marvelslop",
	"""Take less damage to avoid being killed""<br/>-Call of Duty Modern Warfare 2",
	"""Never do anything out of hunger, not even eating""<br/>-Frank Semyon",
	"""War does not determine who is right, only who is based""<br/>-Bertrand Russell",
	"""You can make a throne of bayonets, but you cant sit on it for long. Because butt will hurt""<br/>-Boris Yeltsin",
	"""If I need your body I'll fuck it.""<br/>-Keanu Reeves",
	"""What a shame.""<br/>-JC Denton",
	"""All you had to do was follow the damn train, CJ!""<br/>-Big Smoke",
	"""Die, bitch!""<br/>-Unreal Tournament",
	"""Petah, the horse is here""<br/>-Louis Griffin",
	"""Oh shit, I'm sorry""<br/>-Steve Rambo",
	"""Revolver Ocelot.""<br/>-Revolver Ocelot(Revolver Ocelot)",
	"""NO! THAT IS NOT SOLID SNAKE!""<br/>-Iroquois Pliskin",
	"""A dud!?""<br/>-Navy SEAL",
	"""Babobeh-bopbopahdop-babababa<br/>Babedi-babobeh-babopbedop-bababapi""<br/>-Scatman",
	"""Help me I'm locked in the basement forced to write death quotes""<br/>-No one, don't worry about it.",
	"""Fuck you.""<br/>-Leather man",
	"""Remember this eternal words: Ass we can.<br/>-Billy Herrington",
	"""I dunno.""<br/>-Destroyox2",
	"""I'm about to commit a warcrime on your dick""<br/>-Holt",
	"""Because I'm not dyslexic and this is not the art of flight""<br/>-lelop",
	"""According to all known laws of aviations there is no way a bee should be able to fly.""<br/>-Bee Movie",
	"""Get Fucked Little Girl I'm Playing Arma""<br/>-Exabit",
	"""Shaw!""<br/>-Hornet",
    """No, I don't think it's a contradiction. It's a, uh, spiritual journey. You're tested. But it's like they say, the Devil is in the details.""<br/>-Unknown Luddic Path Engineer",
	"""ENEMY INFANTRY SPOTTED!""<br/>-Commander, Battlefield 2",
	"""Rebinding G is like wearing a rubber, its always a good idea and doesnt nearly feel as good""<br/>-lelop",
	"""You're on a funny little adventure aren't you""<br/>-Exabit",
	"""Guys the fog is coming btw""<br/>-Snubby",
	"""KARMIC JUSTICE, I TOLD YOU<br/>THE MONKEY. ITS PAW""<br/>-Snubby
];

["<t color='#ffffff' size='.8'>"+(selectRandom quotes)+"</t>",-1,-1,10,1,0,789] spawn BIS_fnc_dynamicText;